FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Install FULL ML requirements
COPY requirements-worker.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["celery", "-A", "worker.worker", "worker", "--loglevel=info", "-c", "1"]